%% Descriptive statistics and variance analysis
clear;
clc;
close all;

scriptPath = mfilename('fullpath');
projectRoot = fileparts(fileparts(scriptPath));

dataDir = fullfile(projectRoot, 'CW-Data');
tableDir = fullfile(projectRoot, 'results', 'tables');
figureDir = fullfile(projectRoot, 'results', 'figures');

if ~exist(tableDir, 'dir')
    mkdir(tableDir);
end

if ~exist(figureDir, 'dir')
    mkdir(figureDir);
end

%% Dataset configuration

users = compose('U%02d', 1:10);

domains = {
    'FreqD',       43
    'TimeD',       88
    'TimeD_FreqD', 131
};

days = {'FDay', 'MDay'};

summaryRows = cell(0, 10);
summaryRow = 1;

driftRows = cell(0, 6);
driftRow = 1;

fprintf('\nStage 2 - Descriptive and Variance Analysis\n');
fprintf('===========================================\n\n');

%% Analyse each feature domain

for d = 1:size(domains, 1)

    domain = domains{d, 1};
    featureCount = domains{d, 2};

    fprintf('Domain: %s\n', domain);

    dayData = cell(2, 1);
    dayLabels = cell(2, 1);
    userMatrices = cell(10, 2);

    %% Load both days

    for dayIndex = 1:2

        dayName = days{dayIndex};

        XAll = [];
        labels = [];

        for u = 1:numel(users)

            userID = users{u};

            filePath = fullfile( ...
                dataDir, ...
                sprintf('%s_Acc_%s_%s.mat', ...
                userID, domain, dayName));

            S = load(filePath);

            variableNames = fieldnames(S);
            X = S.(variableNames{1});

            if size(X, 2) ~= featureCount
                error('Unexpected feature count in %s', filePath);
            end

            userMatrices{u, dayIndex} = X;

            XAll = [
                XAll;
                X
            ];

            labels = [
                labels;
                repmat(u, size(X, 1), 1)
            ];
        end

        dayData{dayIndex} = XAll;
        dayLabels{dayIndex} = labels;

        %% Descriptive statistics

        featureNumber = (1:featureCount)';

        featureMean = mean(XAll, 1)';
        featureMedian = median(XAll, 1)';
        featureSD = std(XAll, 0, 1)';
        featureVariance = var(XAll, 0, 1)';
        featureMinimum = min(XAll, [], 1)';
        featureMaximum = max(XAll, [], 1)';
        featureRange = featureMaximum - featureMinimum;

        DescriptiveStatistics = table( ...
            featureNumber, ...
            featureMean, ...
            featureMedian, ...
            featureSD, ...
            featureVariance, ...
            featureMinimum, ...
            featureMaximum, ...
            featureRange, ...
            'VariableNames', { ...
            'Feature', ...
            'Mean', ...
            'Median', ...
            'StandardDeviation', ...
            'Variance', ...
            'Minimum', ...
            'Maximum', ...
            'Range' ...
            });

        descriptiveFile = fullfile( ...
            tableDir, ...
            sprintf('descriptive_%s_%s.csv', ...
            domain, dayName));

        writetable(DescriptiveStatistics, descriptiveFile);

        %% Intra-user variance

        userVariance = zeros(10, featureCount);
        userMean = zeros(10, featureCount);

        for u = 1:10

            XUser = userMatrices{u, dayIndex};

            userVariance(u, :) = ...
                var(XUser, 0, 1);

            userMean(u, :) = ...
                mean(XUser, 1);
        end

        meanIntraVariance = ...
            mean(userVariance, 1);

        medianIntraVariance = ...
            median(userVariance, 1);

        %% Inter-user variance

        interUserVariance = ...
            var(userMean, 0, 1);

        %% Discriminative ratio

        interIntraRatio = ...
            interUserVariance ./ ...
            (meanIntraVariance + eps);

        VarianceMetrics = table( ...
            featureNumber, ...
            meanIntraVariance', ...
            medianIntraVariance', ...
            interUserVariance', ...
            interIntraRatio', ...
            'VariableNames', { ...
            'Feature', ...
            'MeanIntraUserVariance', ...
            'MedianIntraUserVariance', ...
            'InterUserVariance', ...
            'InterIntraRatio' ...
            });

        varianceFile = fullfile( ...
            tableDir, ...
            sprintf('variance_metrics_%s_%s.csv', ...
            domain, dayName));

        writetable(VarianceMetrics, varianceFile);

        %% Rank descriptive features

        [sortedRatio, order] = ...
            sort(interIntraRatio, 'descend');

        topCount = min(15, featureCount);

        TopFeatures = table( ...
            (1:topCount)', ...
            order(1:topCount)', ...
            sortedRatio(1:topCount)', ...
            interUserVariance(order(1:topCount))', ...
            meanIntraVariance(order(1:topCount))', ...
            'VariableNames', { ...
            'Rank', ...
            'Feature', ...
            'InterIntraRatio', ...
            'InterUserVariance', ...
            'MeanIntraUserVariance' ...
            });

        topFeatureFile = fullfile( ...
            tableDir, ...
            sprintf('top_variance_features_%s_%s.csv', ...
            domain, dayName));

        writetable(TopFeatures, topFeatureFile);

        %% Domain/day summary

        summaryRows(summaryRow, :) = { ...
            domain, ...
            dayName, ...
            featureCount, ...
            mean(interIntraRatio), ...
            median(interIntraRatio), ...
            max(interIntraRatio), ...
            mean(meanIntraVariance), ...
            mean(interUserVariance), ...
            order(1), ...
            sortedRatio(1) ...
            };

        summaryRow = summaryRow + 1;

        %% Figure - inter/intra ratio

        fig1 = figure('Visible', 'off');

        plot( ...
            1:featureCount, ...
            interIntraRatio, ...
            'LineWidth', 1.2);

        xlabel('Feature Index');
        ylabel('Inter / Intra Variance Ratio');

        title(sprintf( ...
            '%s %s - Inter/Intra Variance Ratio', ...
            domain, dayName));

        grid on;

        exportgraphics( ...
            fig1, ...
            fullfile( ...
            figureDir, ...
            sprintf('variance_ratio_%s_%s.png', ...
            domain, dayName)), ...
            'Resolution', 300);

        close(fig1);

        %% Figure - intra vs inter variance

        fig2 = figure('Visible', 'off');

        plot( ...
            1:featureCount, ...
            log10(meanIntraVariance + eps), ...
            'LineWidth', 1.2);

        hold on;

        plot( ...
            1:featureCount, ...
            log10(interUserVariance + eps), ...
            'LineWidth', 1.2);

        hold off;

        xlabel('Feature Index');
        ylabel('log10(Variance)');

        legend( ...
            'Mean intra-user variance', ...
            'Inter-user variance', ...
            'Location', 'best');

        title(sprintf( ...
            '%s %s - Within vs Between User Variability', ...
            domain, dayName));

        grid on;

        exportgraphics( ...
            fig2, ...
            fullfile( ...
            figureDir, ...
            sprintf('intra_inter_%s_%s.png', ...
            domain, dayName)), ...
            'Resolution', 300);

        close(fig2);

    end

    %% Cross-day user drift

    % Scaling is estimated from FDay only.
    XReference = dayData{1};

    scaleSD = std(XReference, 0, 1);
    scaleSD(scaleSD == 0) = 1;

    for u = 1:10

        XF = userMatrices{u, 1};
        XM = userMatrices{u, 2};

        meanF = mean(XF, 1);
        meanM = mean(XM, 1);

        rawDistance = ...
            norm(meanF - meanM);

        normalizedDifference = ...
            (meanF - meanM) ./ scaleSD;

        normalizedDistance = ...
            norm(normalizedDifference);

        meanAbsoluteShift = ...
            mean(abs(normalizedDifference));

        exactDuplicate = ...
            isequal(XF, XM);

        driftRows(driftRow, :) = { ...
            users{u}, ...
            domain, ...
            rawDistance, ...
            normalizedDistance, ...
            meanAbsoluteShift, ...
            exactDuplicate ...
            };

        driftRow = driftRow + 1;
    end

end

%% Save domain summary

DomainVarianceSummary = cell2table( ...
    summaryRows, ...
    'VariableNames', { ...
    'Domain', ...
    'Day', ...
    'FeatureCount', ...
    'MeanInterIntraRatio', ...
    'MedianInterIntraRatio', ...
    'MaximumInterIntraRatio', ...
    'MeanIntraVariance', ...
    'MeanInterVariance', ...
    'BestFeature', ...
    'BestFeatureRatio' ...
    });

writetable( ...
    DomainVarianceSummary, ...
    fullfile(tableDir, ...
    'variance_domain_summary.csv'));

%% Save cross-day drift

CrossDayDrift = cell2table( ...
    driftRows, ...
    'VariableNames', { ...
    'User', ...
    'Domain', ...
    'RawCentroidDistance', ...
    'NormalizedCentroidDistance', ...
    'MeanAbsoluteNormalizedShift', ...
    'ExactDuplicate' ...
    });

writetable( ...
    CrossDayDrift, ...
    fullfile(tableDir, ...
    'cross_day_user_drift.csv'));

%% Cross-day drift figure

domainNames = {
    'FreqD'
    'TimeD'
    'TimeD_FreqD'
};

driftMatrix = zeros(10, 3);

for d = 1:3

    idx = strcmp( ...
        CrossDayDrift.Domain, ...
        domainNames{d});

    current = CrossDayDrift(idx, :);

    driftMatrix(:, d) = ...
        current.NormalizedCentroidDistance;
end

fig3 = figure('Visible', 'off');

bar(driftMatrix);

xlabel('User');
ylabel('Normalized FDay-MDay Centroid Distance');

xticks(1:10);
xticklabels(users);

legend( ...
    'Frequency', ...
    'Time', ...
    'Combined', ...
    'Location', 'best');

title('Cross-Day Behavioural Drift by User');

grid on;

exportgraphics( ...
    fig3, ...
    fullfile( ...
    figureDir, ...
    'cross_day_user_drift.png'), ...
    'Resolution', 300);

close(fig3);

%% Console summary

fprintf('\nVariance analysis complete.\n\n');

disp(DomainVarianceSummary);

fprintf('\nTop feature for each domain/day:\n');

for r = 1:height(DomainVarianceSummary)

    fprintf( ...
        '%-12s %-5s -> Feature %d, ratio %.4f\n', ...
        DomainVarianceSummary.Domain{r}, ...
        DomainVarianceSummary.Day{r}, ...
        DomainVarianceSummary.BestFeature(r), ...
        DomainVarianceSummary.BestFeatureRatio(r));
end

fprintf('\nUsers with exact cross-day duplicate data:\n');

duplicateRows = ...
    CrossDayDrift(CrossDayDrift.ExactDuplicate, :);

if isempty(duplicateRows)

    fprintf('None\n');

else

    disp(duplicateRows(:, { ...
        'User', ...
        'Domain', ...
        'ExactDuplicate' ...
        }));
end

fprintf('\nGenerated Stage 2 evidence successfully.\n');