%% Baseline multiclass neural network
clear;
clc;
close all;

scriptPath = mfilename('fullpath');
projectRoot = fileparts(fileparts(scriptPath));

dataDir = fullfile(projectRoot, 'CW-Data');
tableDir = fullfile(projectRoot, 'results', 'tables');
figureDir = fullfile(projectRoot, 'results', 'figures');

if ~exist(tableDir, 'dir')
    mkdir(tableDir);
end

if ~exist(figureDir, 'dir')
    mkdir(figureDir);
end

%% Configuration

users = compose('U%02d', 1:10);

domains = {
    'FreqD'
    'TimeD'
    'TimeD_FreqD'
};

hiddenNeurons = 24;
developmentRepeats = 5;
finalRepeats = 5;

validationSamplesPerUser = 8;
maxEpochs = 400;

fprintf('\nStage 4 - Baseline Neural Network\n');
fprintf('=================================\n\n');

fprintf('Model: 10-class pattern recognition network\n');
fprintf('Hidden neurons: %d\n', hiddenNeurons);
fprintf('Development repeats: %d\n', developmentRepeats);
fprintf('Validation samples per user: %d\n\n', ...
    validationSamplesPerUser);

%% FDay-only domain selection

developmentRows = cell(0, 11);
developmentRow = 1;

for d = 1:numel(domains)

    domain = domains{d};

    fprintf('Development testing: %s\n', domain);

    [X, labels] = loadDomainData( ...
        dataDir, ...
        domain, ...
        'FDay', ...
        users);

    for repeat = 1:developmentRepeats

        rng(4100 + d * 100 + repeat, 'twister');

        trainMask = false(size(labels));
        validationMask = false(size(labels));

        %% Stratified FDay split

        for u = 1:10

            userIndices = find(labels == u);

            randomOrder = ...
                userIndices(randperm(numel(userIndices)));

            validationIndices = ...
                randomOrder(1:validationSamplesPerUser);

            trainingIndices = ...
                randomOrder(validationSamplesPerUser + 1:end);

            validationMask(validationIndices) = true;
            trainMask(trainingIndices) = true;
        end

        XTrain = X(trainMask, :);
        yTrain = labels(trainMask);

        XValidation = X(validationMask, :);
        yValidation = labels(validationMask);

        %% Standardisation fitted on training data

        mu = mean(XTrain, 1);
        sigma = std(XTrain, 0, 1);

        sigma(sigma == 0) = 1;

        XTrainZ = ...
            (XTrain - mu) ./ sigma;

        XValidationZ = ...
            (XValidation - mu) ./ sigma;

        %% Baseline neural network

        network = patternnet( ...
            hiddenNeurons, ...
            'trainscg');

        network.performFcn = 'crossentropy';
        network.divideFcn = 'dividetrain';

        network.trainParam.epochs = maxEpochs;
        network.trainParam.showWindow = false;
        network.trainParam.showCommandLine = false;

        % External standardisation is already applied.
        network.inputs{1}.processFcns = {};

        targets = ...
            full(ind2vec(yTrain'));

        network = train( ...
            network, ...
            XTrainZ', ...
            targets);

        validationScores = ...
            network(XValidationZ');

        metrics = authenticationMetrics( ...
            yValidation, ...
            validationScores);

        developmentRows(developmentRow, :) = { ...
            domain, ...
            repeat, ...
            metrics.Accuracy, ...
            metrics.MacroPrecision, ...
            metrics.MacroRecall, ...
            metrics.MacroF1, ...
            metrics.MacroSpecificity, ...
            metrics.MeanFAR, ...
            metrics.MeanFRR, ...
            metrics.MeanEER, ...
            metrics.MeanAUC ...
            };

        developmentRow = developmentRow + 1;
    end
end

%% Save development runs

DevelopmentRuns = cell2table( ...
    developmentRows, ...
    'VariableNames', { ...
    'Domain', ...
    'Repeat', ...
    'Accuracy', ...
    'MacroPrecision', ...
    'MacroRecall', ...
    'MacroF1', ...
    'MacroSpecificity', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC' ...
    });

writetable( ...
    DevelopmentRuns, ...
    fullfile( ...
    tableDir, ...
    'baseline_domain_development_runs.csv'));

%% Summarise feature domains

summaryRows = cell(0, 10);

for d = 1:numel(domains)

    domain = domains{d};

    idx = strcmp( ...
        DevelopmentRuns.Domain, ...
        domain);

    current = DevelopmentRuns(idx, :);

    summaryRows(d, :) = { ...
        domain, ...
        mean(current.Accuracy), ...
        std(current.Accuracy), ...
        mean(current.MacroF1), ...
        std(current.MacroF1), ...
        mean(current.MeanFAR), ...
        mean(current.MeanFRR), ...
        mean(current.MeanEER), ...
        mean(current.MeanAUC), ...
        height(current) ...
        };
end

DevelopmentSummary = cell2table( ...
    summaryRows, ...
    'VariableNames', { ...
    'Domain', ...
    'MeanAccuracy', ...
    'SDAccuracy', ...
    'MeanMacroF1', ...
    'SDMacroF1', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC', ...
    'Repeats' ...
    });

writetable( ...
    DevelopmentSummary, ...
    fullfile( ...
    tableDir, ...
    'baseline_domain_development_summary.csv'));

%% Select domain using FDay Macro-F1

[~, bestDomainIndex] = ...
    max(DevelopmentSummary.MeanMacroF1);

selectedDomain = ...
    DevelopmentSummary.Domain{bestDomainIndex};

fprintf('\nFDay development results:\n\n');

disp(DevelopmentSummary);

fprintf( ...
    '\nSelected feature domain: %s\n', ...
    selectedDomain);

fprintf( ...
    'Selection criterion: highest FDay Macro-F1\n\n');

%% Figure - development Macro-F1

fig1 = figure('Visible', 'off');

bar(DevelopmentSummary.MeanMacroF1);

xticks(1:numel(domains));

xticklabels({
    'Frequency'
    'Time'
    'Combined'
});

ylabel('Mean Macro-F1');
title('FDay Neural Network Domain Comparison');

grid on;

exportgraphics( ...
    fig1, ...
    fullfile( ...
    figureDir, ...
    'baseline_domain_macro_f1.png'), ...
    'Resolution', 300);

close(fig1);

%% Figure - development EER

fig2 = figure('Visible', 'off');

bar(DevelopmentSummary.MeanEER);

xticks(1:numel(domains));

xticklabels({
    'Frequency'
    'Time'
    'Combined'
});

ylabel('Mean EER');
title('FDay Development Equal Error Rate');

grid on;

exportgraphics( ...
    fig2, ...
    fullfile( ...
    figureDir, ...
    'baseline_domain_eer.png'), ...
    'Resolution', 300);

close(fig2);

%% Locked cross-day baseline evaluation

fprintf('Cross-day baseline evaluation\n');
fprintf('Training: FDay\n');
fprintf('Testing : MDay\n');
fprintf('Domain  : %s\n\n', selectedDomain);

[XFDay, yFDay] = loadDomainData( ...
    dataDir, ...
    selectedDomain, ...
    'FDay', ...
    users);

[XMDay, yMDay] = loadDomainData( ...
    dataDir, ...
    selectedDomain, ...
    'MDay', ...
    users);

crossDayRows = cell(0, 11);
crossDayUserRows = cell(0, 10);

crossDayRow = 1;
crossDayUserRow = 1;

confusionTotal = zeros(10, 10);

for repeat = 1:finalRepeats

    fprintf( ...
        'Cross-day repeat %d/%d\n', ...
        repeat, ...
        finalRepeats);

    rng(8100 + repeat, 'twister');

    %% FDay standardisation

    mu = mean(XFDay, 1);
    sigma = std(XFDay, 0, 1);

    sigma(sigma == 0) = 1;

    XTrainZ = ...
        (XFDay - mu) ./ sigma;

    XTestZ = ...
        (XMDay - mu) ./ sigma;

    %% Train on all FDay

    network = patternnet( ...
        hiddenNeurons, ...
        'trainscg');

    network.performFcn = 'crossentropy';
    network.divideFcn = 'dividetrain';

    network.trainParam.epochs = maxEpochs;
    network.trainParam.showWindow = false;
    network.trainParam.showCommandLine = false;

    network.inputs{1}.processFcns = {};

    targets = ...
        full(ind2vec(yFDay'));

    network = train( ...
        network, ...
        XTrainZ', ...
        targets);

    %% MDay evaluation

    scores = ...
        network(XTestZ');

    [metrics, userMetrics, predictedLabels] = ...
        authenticationMetrics( ...
        yMDay, ...
        scores);

    crossDayRows(crossDayRow, :) = { ...
        selectedDomain, ...
        repeat, ...
        metrics.Accuracy, ...
        metrics.MacroPrecision, ...
        metrics.MacroRecall, ...
        metrics.MacroF1, ...
        metrics.MacroSpecificity, ...
        metrics.MeanFAR, ...
        metrics.MeanFRR, ...
        metrics.MeanEER, ...
        metrics.MeanAUC ...
        };

    crossDayRow = crossDayRow + 1;

    for u = 1:10

        crossDayUserRows(crossDayUserRow, :) = { ...
            repeat, ...
            u, ...
            userMetrics.Accuracy(u), ...
            userMetrics.Precision(u), ...
            userMetrics.Recall(u), ...
            userMetrics.Specificity(u), ...
            userMetrics.F1(u), ...
            userMetrics.FAR(u), ...
            userMetrics.FRR(u), ...
            userMetrics.EER(u) ...
            };

        crossDayUserRow = ...
            crossDayUserRow + 1;
    end

    confusionTotal = ...
        confusionTotal + ...
        confusionmat( ...
        yMDay, ...
        predictedLabels, ...
        'Order', ...
        1:10);
end

%% Save cross-day runs

CrossDayRuns = cell2table( ...
    crossDayRows, ...
    'VariableNames', { ...
    'Domain', ...
    'Repeat', ...
    'Accuracy', ...
    'MacroPrecision', ...
    'MacroRecall', ...
    'MacroF1', ...
    'MacroSpecificity', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC' ...
    });

writetable( ...
    CrossDayRuns, ...
    fullfile( ...
    tableDir, ...
    'baseline_crossday_runs.csv'));

%% Cross-day summary

BaselineSummary = table( ...
    string(selectedDomain), ...
    hiddenNeurons, ...
    finalRepeats, ...
    mean(CrossDayRuns.Accuracy), ...
    std(CrossDayRuns.Accuracy), ...
    mean(CrossDayRuns.MacroPrecision), ...
    mean(CrossDayRuns.MacroRecall), ...
    mean(CrossDayRuns.MacroF1), ...
    std(CrossDayRuns.MacroF1), ...
    mean(CrossDayRuns.MacroSpecificity), ...
    mean(CrossDayRuns.MeanFAR), ...
    mean(CrossDayRuns.MeanFRR), ...
    mean(CrossDayRuns.MeanEER), ...
    mean(CrossDayRuns.MeanAUC), ...
    'VariableNames', { ...
    'Domain', ...
    'HiddenNeurons', ...
    'Repeats', ...
    'MeanAccuracy', ...
    'SDAccuracy', ...
    'MeanMacroPrecision', ...
    'MeanMacroRecall', ...
    'MeanMacroF1', ...
    'SDMacroF1', ...
    'MeanSpecificity', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC' ...
    });

writetable( ...
    BaselineSummary, ...
    fullfile( ...
    tableDir, ...
    'baseline_crossday_summary.csv'));

%% Per-user cross-day results

CrossDayUserRuns = cell2table( ...
    crossDayUserRows, ...
    'VariableNames', { ...
    'Repeat', ...
    'User', ...
    'Accuracy', ...
    'Precision', ...
    'Recall', ...
    'Specificity', ...
    'F1', ...
    'FAR', ...
    'FRR', ...
    'EER' ...
    });

writetable( ...
    CrossDayUserRuns, ...
    fullfile( ...
    tableDir, ...
    'baseline_crossday_user_runs.csv'));

userSummaryRows = cell(10, 10);

for u = 1:10

    idx = ...
        CrossDayUserRuns.User == u;

    current = ...
        CrossDayUserRuns(idx, :);

    userSummaryRows(u, :) = { ...
        users{u}, ...
        mean(current.Accuracy), ...
        mean(current.Precision), ...
        mean(current.Recall), ...
        mean(current.Specificity), ...
        mean(current.F1), ...
        mean(current.FAR), ...
        mean(current.FRR), ...
        mean(current.EER), ...
        std(current.F1) ...
        };
end

CrossDayUserSummary = cell2table( ...
    userSummaryRows, ...
    'VariableNames', { ...
    'User', ...
    'Accuracy', ...
    'Precision', ...
    'Recall', ...
    'Specificity', ...
    'F1', ...
    'FAR', ...
    'FRR', ...
    'EER', ...
    'SDF1' ...
    });

writetable( ...
    CrossDayUserSummary, ...
    fullfile( ...
    tableDir, ...
    'baseline_crossday_user_summary.csv'));

%% Mean confusion matrix

meanConfusion = ...
    confusionTotal ./ finalRepeats;

fig3 = figure('Visible', 'off');

imagesc(meanConfusion);

colorbar;

xlabel('Predicted User');
ylabel('True User');

xticks(1:10);
yticks(1:10);

xticklabels(users);
yticklabels(users);

title(sprintf( ...
    'Baseline Cross-Day Confusion Matrix - %s', ...
    selectedDomain));

exportgraphics( ...
    fig3, ...
    fullfile( ...
    figureDir, ...
    'baseline_crossday_confusion.png'), ...
    'Resolution', 300);

close(fig3);

%% Per-user error-rate figure

errorValues = [
    CrossDayUserSummary.FAR, ...
    CrossDayUserSummary.FRR, ...
    CrossDayUserSummary.EER
];

fig4 = figure('Visible', 'off');

bar(errorValues);

xlabel('User');
ylabel('Error Rate');

xticks(1:10);
xticklabels(users);

legend( ...
    'FAR', ...
    'FRR', ...
    'EER', ...
    'Location', ...
    'best');

title('Baseline Cross-Day Authentication Errors');

grid on;

exportgraphics( ...
    fig4, ...
    fullfile( ...
    figureDir, ...
    'baseline_crossday_user_errors.png'), ...
    'Resolution', 300);

close(fig4);

%% Console summary

fprintf('\nBaseline cross-day summary:\n\n');

disp(BaselineSummary);

fprintf('\nPer-user MDay performance:\n\n');

disp(CrossDayUserSummary);

fprintf('\nMethodology:\n');
fprintf('Feature domain selected using FDay only.\n');
fprintf('MDay was not used during domain selection.\n');
fprintf('Final baseline network trained using all FDay samples.\n');
fprintf('Cross-day performance evaluated using MDay.\n');

fprintf('\nGenerated Stage 4 evidence successfully.\n');

%% Local functions

function [XAll, labels] = ...
    loadDomainData(dataDir, domain, dayName, users)

    XAll = [];
    labels = [];

    for u = 1:numel(users)

        filePath = fullfile( ...
            dataDir, ...
            sprintf( ...
            '%s_Acc_%s_%s.mat', ...
            users{u}, ...
            domain, ...
            dayName));

        S = load(filePath);

        variableNames = fieldnames(S);

        X = S.(variableNames{1});

        XAll = [
            XAll;
            X
        ];

        labels = [
            labels;
            repmat(u, size(X, 1), 1)
        ];
    end
end


function [metrics, userTable, predictedLabels] = ...
    authenticationMetrics(trueLabels, scores)

    classCount = 10;

    predictedLabels = ...
        vec2ind(scores)';

    accuracy = ...
        mean(predictedLabels == trueLabels);

    userAccuracy = zeros(classCount, 1);
    precision = zeros(classCount, 1);
    recall = zeros(classCount, 1);
    specificity = zeros(classCount, 1);
    f1 = zeros(classCount, 1);
    far = zeros(classCount, 1);
    frr = zeros(classCount, 1);
    eer = zeros(classCount, 1);
    auc = zeros(classCount, 1);

    for u = 1:classCount

        genuine = ...
            trueLabels == u;

        acceptedAsUser = ...
            predictedLabels == u;

        TP = sum(genuine & acceptedAsUser);
        FN = sum(genuine & ~acceptedAsUser);

        FP = sum(~genuine & acceptedAsUser);
        TN = sum(~genuine & ~acceptedAsUser);

        userAccuracy(u) = ...
            (TP + TN) / ...
            (TP + TN + FP + FN + eps);

        precision(u) = ...
            TP / ...
            (TP + FP + eps);

        recall(u) = ...
            TP / ...
            (TP + FN + eps);

        specificity(u) = ...
            TN / ...
            (TN + FP + eps);

        f1(u) = ...
            2 * precision(u) * recall(u) / ...
            (precision(u) + recall(u) + eps);

        far(u) = ...
            FP / ...
            (FP + TN + eps);

        frr(u) = ...
            FN / ...
            (TP + FN + eps);

        binaryLabels = ...
            double(genuine);

        userScores = ...
            scores(u, :)';

        [rocFPR, rocTPR, ~, aucValue] = ...
            perfcurve( ...
            binaryLabels, ...
            userScores, ...
            1);

        rocFNR = ...
            1 - rocTPR;

        [~, eerIndex] = ...
            min(abs(rocFPR - rocFNR));

        eer(u) = ...
            (rocFPR(eerIndex) + ...
            rocFNR(eerIndex)) / 2;

        auc(u) = aucValue;
    end

    metrics = struct();

    metrics.Accuracy = accuracy;

    metrics.MacroPrecision = ...
        mean(precision);

    metrics.MacroRecall = ...
        mean(recall);

    metrics.MacroF1 = ...
        mean(f1);

    metrics.MacroSpecificity = ...
        mean(specificity);

    metrics.MeanFAR = ...
        mean(far);

    metrics.MeanFRR = ...
        mean(frr);

    metrics.MeanEER = ...
        mean(eer);

    metrics.MeanAUC = ...
        mean(auc);

    User = (1:classCount)';

    userTable = table( ...
        User, ...
        userAccuracy, ...
        precision, ...
        recall, ...
        specificity, ...
        f1, ...
        far, ...
        frr, ...
        eer, ...
        auc, ...
        'VariableNames', { ...
        'User', ...
        'Accuracy', ...
        'Precision', ...
        'Recall', ...
        'Specificity', ...
        'F1', ...
        'FAR', ...
        'FRR', ...
        'EER', ...
        'AUC' ...
        });
end