%% Supervised feature selection using mRMR
clear;
clc;
close all;

scriptPath = mfilename('fullpath');
projectRoot = fileparts(fileparts(scriptPath));

dataDir = fullfile(projectRoot, 'CW-Data');
tableDir = fullfile(projectRoot, 'results', 'tables');
figureDir = fullfile(projectRoot, 'results', 'figures');

if ~exist(tableDir, 'dir')
    mkdir(tableDir);
end

if ~exist(figureDir, 'dir')
    mkdir(figureDir);
end

%% Configuration

users = compose('U%02d', 1:10);

domain = 'TimeD_FreqD';
hiddenLayers = [48 24];

featureCounts = [20 40 60 80 100 131];

repeats = 5;
validationSamplesPerUser = 8;
maxEpochs = 400;

fprintf('\nStage 6 - mRMR Feature Selection\n');
fprintf('================================\n\n');

fprintf('Feature domain : %s\n', domain);
fprintf('Architecture   : [48 24]\n');
fprintf('Feature counts : ');

fprintf('%d ', featureCounts);

fprintf('\nRepeats        : %d\n', repeats);
fprintf('Total networks : %d\n\n', ...
    numel(featureCounts) * repeats);

%% Load FDay only

[X, labels] = loadDomainData( ...
    dataDir, ...
    domain, ...
    'FDay', ...
    users);

fprintf('FDay samples   : %d\n', size(X, 1));
fprintf('Original inputs: %d\n\n', size(X, 2));

%% Storage

resultRows = cell(0, 13);
resultRow = 1;

rankingRows = cell(0, 4);
rankingRow = 1;

rankingByRepeat = cell(repeats, 1);

%% Repeated development experiment

for repeat = 1:repeats

    fprintf('Repeat %d/%d\n', repeat, repeats);

    %% Identical stratified split for all feature counts

    rng(7200 + repeat, 'twister');

    trainMask = false(size(labels));
    validationMask = false(size(labels));

    for u = 1:10

        userIndices = find(labels == u);

        order = randperm(numel(userIndices));

        validationIndices = ...
            userIndices(order(1:validationSamplesPerUser));

        trainingIndices = ...
            userIndices(order(validationSamplesPerUser + 1:end));

        validationMask(validationIndices) = true;
        trainMask(trainingIndices) = true;
    end

    XTrainFull = X(trainMask, :);
    yTrain = labels(trainMask);

    XValidationFull = X(validationMask, :);
    yValidation = labels(validationMask);

    %% mRMR ranking fitted on training samples only

    [featureRanking, featureScores] = ...
        fscmrmr( ...
        XTrainFull, ...
        categorical(yTrain));

    rankingByRepeat{repeat} = featureRanking;

    for rankPosition = 1:numel(featureRanking)

        featureIndex = ...
            featureRanking(rankPosition);

        rankingRows(rankingRow, :) = { ...
            repeat, ...
            rankPosition, ...
            featureIndex, ...
            featureScores(featureIndex) ...
            };

        rankingRow = rankingRow + 1;
    end

    %% Evaluate different feature counts

    for c = 1:numel(featureCounts)

        featureCount = featureCounts(c);

        selectedFeatures = ...
            featureRanking(1:featureCount);

        XTrain = ...
            XTrainFull(:, selectedFeatures);

        XValidation = ...
            XValidationFull(:, selectedFeatures);

        %% Standardisation using training samples only

        mu = mean(XTrain, 1);
        sigma = std(XTrain, 0, 1);

        sigma(sigma == 0) = 1;

        XTrainZ = ...
            (XTrain - mu) ./ sigma;

        XValidationZ = ...
            (XValidation - mu) ./ sigma;

        %% Neural network

        rng( ...
            8200 + ...
            c * 100 + ...
            repeat, ...
            'twister');

        network = patternnet( ...
            hiddenLayers, ...
            'trainscg');

        network.performFcn = 'crossentropy';
        network.divideFcn = 'dividetrain';

        network.trainParam.epochs = maxEpochs;
        network.trainParam.showWindow = false;
        network.trainParam.showCommandLine = false;

        network.inputs{1}.processFcns = {};

        targets = ...
            full(ind2vec(yTrain'));

        network = train( ...
            network, ...
            XTrainZ', ...
            targets);

        validationScores = ...
            network(XValidationZ');

        metrics = ...
            authenticationMetrics( ...
            yValidation, ...
            validationScores);

        resultRows(resultRow, :) = { ...
            featureCount, ...
            repeat, ...
            metrics.Accuracy, ...
            metrics.MacroPrecision, ...
            metrics.MacroRecall, ...
            metrics.MacroF1, ...
            metrics.MacroSpecificity, ...
            metrics.MeanFAR, ...
            metrics.MeanFRR, ...
            metrics.MeanEER, ...
            metrics.MeanAUC, ...
            size(XTrain, 1), ...
            size(XTrain, 2) ...
            };

        resultRow = resultRow + 1;
    end
end

%% Save mRMR rankings

MRMRRankings = cell2table( ...
    rankingRows, ...
    'VariableNames', { ...
    'Repeat', ...
    'Rank', ...
    'Feature', ...
    'MRMRScore' ...
    });

writetable( ...
    MRMRRankings, ...
    fullfile( ...
    tableDir, ...
    'mrmr_rankings_by_repeat.csv'));

%% Save all feature-count experiments

FeatureSelectionRuns = cell2table( ...
    resultRows, ...
    'VariableNames', { ...
    'FeatureCount', ...
    'Repeat', ...
    'Accuracy', ...
    'MacroPrecision', ...
    'MacroRecall', ...
    'MacroF1', ...
    'MacroSpecificity', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC', ...
    'TrainingSamples', ...
    'InputFeatures' ...
    });

writetable( ...
    FeatureSelectionRuns, ...
    fullfile( ...
    tableDir, ...
    'feature_selection_runs.csv'));

%% Summarise candidate feature counts

summaryRows = cell(numel(featureCounts), 12);

for c = 1:numel(featureCounts)

    featureCount = featureCounts(c);

    idx = ...
        FeatureSelectionRuns.FeatureCount == featureCount;

    current = ...
        FeatureSelectionRuns(idx, :);

    summaryRows(c, :) = { ...
        featureCount, ...
        mean(current.Accuracy), ...
        std(current.Accuracy), ...
        mean(current.MacroPrecision), ...
        mean(current.MacroRecall), ...
        mean(current.MacroF1), ...
        std(current.MacroF1), ...
        mean(current.MacroSpecificity), ...
        mean(current.MeanFAR), ...
        mean(current.MeanFRR), ...
        mean(current.MeanEER), ...
        mean(current.MeanAUC) ...
        };
end

FeatureSelectionSummary = cell2table( ...
    summaryRows, ...
    'VariableNames', { ...
    'FeatureCount', ...
    'MeanAccuracy', ...
    'SDAccuracy', ...
    'MeanMacroPrecision', ...
    'MeanMacroRecall', ...
    'MeanMacroF1', ...
    'SDMacroF1', ...
    'MeanSpecificity', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC' ...
    });

%% Rank candidates

FeatureSelectionSummary = ...
    sortrows( ...
        FeatureSelectionSummary, ...
        {'MeanMacroF1', 'MeanEER', 'FeatureCount'}, ...
        {'descend', 'ascend', 'ascend'});

Rank = ...
    (1:height(FeatureSelectionSummary))';

FeatureSelectionSummary = ...
    addvars( ...
        FeatureSelectionSummary, ...
        Rank, ...
        'Before', ...
        1);

writetable( ...
    FeatureSelectionSummary, ...
    fullfile( ...
    tableDir, ...
    'feature_selection_summary.csv'));

%% Selected feature count

selectedFeatureCount = ...
    FeatureSelectionSummary.FeatureCount(1);

selectedMacroF1 = ...
    FeatureSelectionSummary.MeanMacroF1(1);

selectedEER = ...
    FeatureSelectionSummary.MeanEER(1);

%% Final mRMR ranking using all FDay
% Used only to define the locked feature list after the
% feature-count hyperparameter has already been selected.

[finalRanking, finalScores] = ...
    fscmrmr( ...
    X, ...
    categorical(labels));

lockedFeatures = ...
    finalRanking(1:selectedFeatureCount);

rankColumn = ...
    (1:selectedFeatureCount)';

featureColumn = ...
    lockedFeatures';

scoreColumn = ...
    finalScores(lockedFeatures)';

LockedFeatures = table( ...
    rankColumn, ...
    featureColumn, ...
    scoreColumn, ...
    'VariableNames', { ...
    'Rank', ...
    'Feature', ...
    'MRMRScore' ...
    });

writetable( ...
    LockedFeatures, ...
    fullfile( ...
    tableDir, ...
    'selected_mrmr_features.csv'));

%% Ranking stability

selectionFrequency = zeros(size(X, 2), 1);

for repeat = 1:repeats

    currentRanking = ...
        rankingByRepeat{repeat};

    currentSelected = ...
        currentRanking(1:selectedFeatureCount);

    selectionFrequency(currentSelected) = ...
        selectionFrequency(currentSelected) + 1;
end

featureIndex = ...
    (1:size(X, 2))';

selectionRate = ...
    selectionFrequency ./ repeats;

RankingStability = table( ...
    featureIndex, ...
    selectionFrequency, ...
    selectionRate, ...
    'VariableNames', { ...
    'Feature', ...
    'TimesSelected', ...
    'SelectionRate' ...
    });

RankingStability = ...
    sortrows( ...
        RankingStability, ...
        {'TimesSelected', 'Feature'}, ...
        {'descend', 'ascend'});

writetable( ...
    RankingStability, ...
    fullfile( ...
    tableDir, ...
    'mrmr_selection_stability.csv'));

%% Save selected setup

SelectedFeatureSetup = table( ...
    string(domain), ...
    string('mRMR'), ...
    selectedFeatureCount, ...
    string('48-24'), ...
    selectedMacroF1, ...
    selectedEER, ...
    'VariableNames', { ...
    'Domain', ...
    'Method', ...
    'FeatureCount', ...
    'Architecture', ...
    'DevelopmentMacroF1', ...
    'DevelopmentEER' ...
    });

writetable( ...
    SelectedFeatureSetup, ...
    fullfile( ...
    tableDir, ...
    'selected_feature_setup.csv'));

%% Figure - Macro-F1

plotSummary = ...
    sortrows( ...
        FeatureSelectionSummary, ...
        'FeatureCount', ...
        'ascend');

fig1 = figure('Visible', 'off');

plot( ...
    plotSummary.FeatureCount, ...
    plotSummary.MeanMacroF1, ...
    '-o', ...
    'LineWidth', ...
    1.5);

xlabel('Number of Selected Features');
ylabel('Mean Macro-F1');

title('FDay mRMR Feature Selection Performance');

grid on;

exportgraphics( ...
    fig1, ...
    fullfile( ...
    figureDir, ...
    'feature_selection_macro_f1.png'), ...
    'Resolution', 300);

close(fig1);

%% Figure - EER

fig2 = figure('Visible', 'off');

plot( ...
    plotSummary.FeatureCount, ...
    plotSummary.MeanEER, ...
    '-o', ...
    'LineWidth', ...
    1.5);

xlabel('Number of Selected Features');
ylabel('Mean EER');

title('FDay mRMR Feature Selection EER');

grid on;

exportgraphics( ...
    fig2, ...
    fullfile( ...
    figureDir, ...
    'feature_selection_eer.png'), ...
    'Resolution', 300);

close(fig2);

%% Figure - performance versus dimensionality

fig3 = figure('Visible', 'off');

bar( ...
    plotSummary.FeatureCount, ...
    plotSummary.MeanMacroF1);

xlabel('Number of Selected Features');
ylabel('Mean Macro-F1');

title('Performance versus Input Dimensionality');

grid on;

exportgraphics( ...
    fig3, ...
    fullfile( ...
    figureDir, ...
    'feature_selection_dimensionality.png'), ...
    'Resolution', 300);

close(fig3);

%% Top stable features figure

topStableCount = min(20, height(RankingStability));

topStable = ...
    RankingStability(1:topStableCount, :);

fig4 = figure('Visible', 'off');

bar( ...
    topStable.TimesSelected);

xlabel('Feature');
ylabel('Times Selected in Top Set');

xticks(1:topStableCount);

xticklabels( ...
    string(topStable.Feature));

xtickangle(45);

title('mRMR Feature Selection Stability');

ylim([0 repeats]);

grid on;

exportgraphics( ...
    fig4, ...
    fullfile( ...
    figureDir, ...
    'mrmr_feature_stability.png'), ...
    'Resolution', 300);

close(fig4);

%% Console output

fprintf('\nFeature selection optimisation complete.\n\n');

disp(FeatureSelectionSummary);

fprintf('\nSelected feature setup:\n');

fprintf('Method       : mRMR\n');

fprintf( ...
    'Features     : %d / %d\n', ...
    selectedFeatureCount, ...
    size(X, 2));

fprintf('Architecture : [48 24]\n');

fprintf( ...
    'Macro-F1     : %.5f\n', ...
    selectedMacroF1);

fprintf( ...
    'Mean EER     : %.5f\n', ...
    selectedEER);

fprintf('\nTop 15 locked features:\n');

disp( ...
    LockedFeatures( ...
    1:min(15, height(LockedFeatures)), :));

fprintf('\nMethodology note:\n');
fprintf('mRMR ranking was fitted separately inside each FDay training split.\n');
fprintf('Validation samples were excluded from feature ranking.\n');
fprintf('MDay was not used for feature-count selection.\n');
fprintf('After selecting the feature count, all FDay samples were used to create the locked ranking.\n');

fprintf('\nGenerated Stage 6 evidence successfully.\n');

%% Local functions

function [XAll, labels] = ...
    loadDomainData(dataDir, domain, dayName, users)

    XAll = [];
    labels = [];

    for u = 1:numel(users)

        filePath = fullfile( ...
            dataDir, ...
            sprintf( ...
            '%s_Acc_%s_%s.mat', ...
            users{u}, ...
            domain, ...
            dayName));

        S = load(filePath);

        variableNames = ...
            fieldnames(S);

        X = ...
            S.(variableNames{1});

        XAll = [
            XAll;
            X
        ];

        labels = [
            labels;
            repmat(u, size(X, 1), 1)
        ];
    end
end


function metrics = ...
    authenticationMetrics(trueLabels, scores)

    classCount = 10;

    predictedLabels = ...
        vec2ind(scores)';

    accuracy = ...
        mean(predictedLabels == trueLabels);

    precision = zeros(classCount, 1);
    recall = zeros(classCount, 1);
    specificity = zeros(classCount, 1);
    f1 = zeros(classCount, 1);
    far = zeros(classCount, 1);
    frr = zeros(classCount, 1);
    eer = zeros(classCount, 1);
    auc = zeros(classCount, 1);

    for u = 1:classCount

        genuine = ...
            trueLabels == u;

        acceptedAsUser = ...
            predictedLabels == u;

        TP = sum(genuine & acceptedAsUser);
        FN = sum(genuine & ~acceptedAsUser);

        FP = sum(~genuine & acceptedAsUser);
        TN = sum(~genuine & ~acceptedAsUser);

        precision(u) = ...
            TP / ...
            (TP + FP + eps);

        recall(u) = ...
            TP / ...
            (TP + FN + eps);

        specificity(u) = ...
            TN / ...
            (TN + FP + eps);

        f1(u) = ...
            2 * precision(u) * recall(u) / ...
            (precision(u) + recall(u) + eps);

        far(u) = ...
            FP / ...
            (FP + TN + eps);

        frr(u) = ...
            FN / ...
            (TP + FN + eps);

        binaryLabels = ...
            double(genuine);

        userScores = ...
            scores(u, :)';

        [rocFPR, rocTPR, ~, aucValue] = ...
            perfcurve( ...
            binaryLabels, ...
            userScores, ...
            1);

        rocFNR = ...
            1 - rocTPR;

        [~, eerIndex] = ...
            min(abs(rocFPR - rocFNR));

        eer(u) = ...
            (rocFPR(eerIndex) + ...
            rocFNR(eerIndex)) / 2;

        auc(u) = aucValue;
    end

    metrics = struct();

    metrics.Accuracy = accuracy;
    metrics.MacroPrecision = mean(precision);
    metrics.MacroRecall = mean(recall);
    metrics.MacroF1 = mean(f1);
    metrics.MacroSpecificity = mean(specificity);
    metrics.MeanFAR = mean(far);
    metrics.MeanFRR = mean(frr);
    metrics.MeanEER = mean(eer);
    metrics.MeanAUC = mean(auc);
end