%% PCA and cross-day dimensionality analysis
clear;
clc;
close all;

scriptPath = mfilename('fullpath');
projectRoot = fileparts(fileparts(scriptPath));

dataDir = fullfile(projectRoot, 'CW-Data');
tableDir = fullfile(projectRoot, 'results', 'tables');
figureDir = fullfile(projectRoot, 'results', 'figures');

if ~exist(tableDir, 'dir')
    mkdir(tableDir);
end

if ~exist(figureDir, 'dir')
    mkdir(figureDir);
end

%% Configuration

users = compose('U%02d', 1:10);

domains = {
    'FreqD',       43
    'TimeD',       88
    'TimeD_FreqD', 131
};

summaryRows = cell(0, 14);
summaryRow = 1;

driftRows = cell(0, 6);
driftRow = 1;

fprintf('\nStage 3 - PCA and Cross-Day Analysis\n');
fprintf('====================================\n\n');

%% Analyse each feature domain

for d = 1:size(domains, 1)

    domain = domains{d, 1};
    expectedFeatures = domains{d, 2};

    fprintf('Processing %s...\n', domain);

    XFDay = [];
    XMDay = [];

    labelsF = [];
    labelsM = [];

    %% Load data

    for u = 1:numel(users)

        userID = users{u};

        fdayFile = fullfile( ...
            dataDir, ...
            sprintf('%s_Acc_%s_FDay.mat', ...
            userID, domain));

        mdayFile = fullfile( ...
            dataDir, ...
            sprintf('%s_Acc_%s_MDay.mat', ...
            userID, domain));

        SF = load(fdayFile);
        SM = load(mdayFile);

        fieldsF = fieldnames(SF);
        fieldsM = fieldnames(SM);

        XF = SF.(fieldsF{1});
        XM = SM.(fieldsM{1});

        if size(XF, 2) ~= expectedFeatures || ...
           size(XM, 2) ~= expectedFeatures

            error('Unexpected feature count for %s', domain);
        end

        XFDay = [
            XFDay;
            XF
        ];

        XMDay = [
            XMDay;
            XM
        ];

        labelsF = [
            labelsF;
            repmat(u, size(XF, 1), 1)
        ];

        labelsM = [
            labelsM;
            repmat(u, size(XM, 1), 1)
        ];
    end

    %% FDay-only standardisation

    featureMean = mean(XFDay, 1);
    featureSD = std(XFDay, 0, 1);

    featureSD(featureSD == 0) = 1;

    ZFDay = ...
        (XFDay - featureMean) ./ featureSD;

    ZMDay = ...
        (XMDay - featureMean) ./ featureSD;

    %% PCA fitted on FDay only

    [coeff, scoreF, latent, ~, explained, pcaMean] = ...
        pca(ZFDay);

    %% Project MDay into the same PCA space

    scoreM = ...
        (ZMDay - pcaMean) * coeff;

    cumulativeVariance = cumsum(explained);

    pc90 = find( ...
        cumulativeVariance >= 90, ...
        1, ...
        'first');

    pc95 = find( ...
        cumulativeVariance >= 95, ...
        1, ...
        'first');

    pc99 = find( ...
        cumulativeVariance >= 99, ...
        1, ...
        'first');

    pc1Variance = explained(1);
    pc2Variance = explained(2);
    pc3Variance = explained(3);

    firstTwoVariance = ...
        sum(explained(1:2));

    firstThreeVariance = ...
        sum(explained(1:3));

    %% Save explained variance

    PC = (1:numel(explained))';

    ExplainedVariance = explained;

    CumulativeVariance = cumulativeVariance;

    ExplainedTable = table( ...
        PC, ...
        ExplainedVariance, ...
        CumulativeVariance);

    writetable( ...
        ExplainedTable, ...
        fullfile( ...
        tableDir, ...
        sprintf('pca_explained_%s.csv', domain)));

    %% Cluster statistics using first three PCs

    numberPCsForSeparation = min(3, size(scoreF, 2));

    F3 = scoreF(:, 1:numberPCsForSeparation);
    M3 = scoreM(:, 1:numberPCsForSeparation);

    centroidF = zeros(10, numberPCsForSeparation);
    centroidM = zeros(10, numberPCsForSeparation);

    withinFValues = [];
    withinMValues = [];

    for u = 1:10

        idxF = labelsF == u;
        idxM = labelsM == u;

        userF = F3(idxF, :);
        userM = M3(idxM, :);

        centroidF(u, :) = mean(userF, 1);
        centroidM(u, :) = mean(userM, 1);

        distanceF = sqrt( ...
            sum( ...
            (userF - centroidF(u, :)).^2, ...
            2));

        distanceM = sqrt( ...
            sum( ...
            (userM - centroidM(u, :)).^2, ...
            2));

        withinFValues = [
            withinFValues;
            distanceF
        ];

        withinMValues = [
            withinMValues;
            distanceM
        ];

        centroidShift = ...
            norm( ...
            centroidF(u, :) - ...
            centroidM(u, :));

        meanSampleShift = ...
            mean( ...
            sqrt( ...
            sum( ...
            (userF - userM).^2, ...
            2)));

        driftRows(driftRow, :) = { ...
            users{u}, ...
            domain, ...
            centroidShift, ...
            meanSampleShift, ...
            norm(centroidF(u, :)), ...
            norm(centroidM(u, :)) ...
            };

        driftRow = driftRow + 1;
    end

    meanWithinF = mean(withinFValues);
    meanWithinM = mean(withinMValues);

    %% Between-user centroid distance

    betweenF = pdist(centroidF, 'euclidean');
    betweenM = pdist(centroidM, 'euclidean');

    meanBetweenF = mean(betweenF);
    meanBetweenM = mean(betweenM);

    minimumBetweenF = min(betweenF);
    minimumBetweenM = min(betweenM);

    separationF = ...
        meanBetweenF / ...
        (meanWithinF + eps);

    separationM = ...
        meanBetweenM / ...
        (meanWithinM + eps);

    %% Cross-day centroid stability

    centroidShifts = sqrt( ...
        sum( ...
        (centroidF - centroidM).^2, ...
        2));

    meanCentroidShift = ...
        mean(centroidShifts);

    maximumCentroidShift = ...
        max(centroidShifts);

    %% Store summary

    summaryRows(summaryRow, :) = { ...
        domain, ...
        expectedFeatures, ...
        pc1Variance, ...
        pc2Variance, ...
        firstTwoVariance, ...
        firstThreeVariance, ...
        pc90, ...
        pc95, ...
        pc99, ...
        separationF, ...
        separationM, ...
        meanCentroidShift, ...
        maximumCentroidShift, ...
        meanBetweenM ...
        };

    summaryRow = summaryRow + 1;

    %% Figure 1 - cumulative explained variance

    fig1 = figure('Visible', 'off');

    plot( ...
        1:numel(cumulativeVariance), ...
        cumulativeVariance, ...
        'LineWidth', 1.5);

    hold on;

    yline(90, '--');
    yline(95, '--');

    hold off;

    xlabel('Principal Component');
    ylabel('Cumulative Explained Variance (%)');

    title(sprintf( ...
        '%s - PCA Explained Variance', ...
        domain));

    ylim([0 100]);

    grid on;

    exportgraphics( ...
        fig1, ...
        fullfile( ...
        figureDir, ...
        sprintf('pca_cumulative_%s.png', ...
        domain)), ...
        'Resolution', 300);

    close(fig1);

    %% Figure 2 - FDay PCA scatter

    fig2 = figure('Visible', 'off');

    hold on;

    for u = 1:10

        idx = labelsF == u;

        scatter( ...
            scoreF(idx, 1), ...
            scoreF(idx, 2), ...
            24, ...
            'filled', ...
            'DisplayName', users{u});
    end

    hold off;

    xlabel(sprintf( ...
        'PC1 (%.1f%%)', ...
        explained(1)));

    ylabel(sprintf( ...
        'PC2 (%.1f%%)', ...
        explained(2)));

    title(sprintf( ...
        '%s - FDay PCA Projection', ...
        domain));

    legend( ...
        'Location', ...
        'eastoutside');

    grid on;

    exportgraphics( ...
        fig2, ...
        fullfile( ...
        figureDir, ...
        sprintf('pca_scatter_%s_FDay.png', ...
        domain)), ...
        'Resolution', 300);

    close(fig2);

    %% Figure 3 - MDay projected into FDay PCA space

    fig3 = figure('Visible', 'off');

    hold on;

    for u = 1:10

        idx = labelsM == u;

        scatter( ...
            scoreM(idx, 1), ...
            scoreM(idx, 2), ...
            24, ...
            'filled', ...
            'DisplayName', users{u});
    end

    hold off;

    xlabel(sprintf( ...
        'FDay PC1 (%.1f%%)', ...
        explained(1)));

    ylabel(sprintf( ...
        'FDay PC2 (%.1f%%)', ...
        explained(2)));

    title(sprintf( ...
        '%s - MDay Projected into FDay PCA Space', ...
        domain));

    legend( ...
        'Location', ...
        'eastoutside');

    grid on;

    exportgraphics( ...
        fig3, ...
        fullfile( ...
        figureDir, ...
        sprintf('pca_scatter_%s_MDay.png', ...
        domain)), ...
        'Resolution', 300);

    close(fig3);

    %% Figure 4 - centroid shift

    fig4 = figure('Visible', 'off');

    bar(centroidShifts);

    xlabel('User');
    ylabel('FDay-MDay Centroid Shift');

    xticks(1:10);
    xticklabels(users);

    title(sprintf( ...
        '%s - Cross-Day PCA Centroid Shift', ...
        domain));

    grid on;

    exportgraphics( ...
        fig4, ...
        fullfile( ...
        figureDir, ...
        sprintf('pca_centroid_shift_%s.png', ...
        domain)), ...
        'Resolution', 300);

    close(fig4);

end

%% Save PCA summary

PCASummary = cell2table( ...
    summaryRows, ...
    'VariableNames', { ...
    'Domain', ...
    'OriginalFeatures', ...
    'PC1VariancePercent', ...
    'PC2VariancePercent', ...
    'PC1PC2VariancePercent', ...
    'First3VariancePercent', ...
    'PCsFor90Percent', ...
    'PCsFor95Percent', ...
    'PCsFor99Percent', ...
    'FDaySeparationRatio', ...
    'MDaySeparationRatio', ...
    'MeanCrossDayCentroidShift', ...
    'MaximumCrossDayCentroidShift', ...
    'MDayMeanBetweenUserDistance' ...
    });

writetable( ...
    PCASummary, ...
    fullfile( ...
    tableDir, ...
    'pca_domain_summary.csv'));

%% Save per-user cross-day PCA drift

PCAUserDrift = cell2table( ...
    driftRows, ...
    'VariableNames', { ...
    'User', ...
    'Domain', ...
    'CentroidShift', ...
    'MeanPairedSampleShift', ...
    'FDayCentroidMagnitude', ...
    'MDayCentroidMagnitude' ...
    });

writetable( ...
    PCAUserDrift, ...
    fullfile( ...
    tableDir, ...
    'pca_user_crossday_drift.csv'));

%% Overall comparison figure

fig5 = figure('Visible', 'off');

comparisonValues = [
    PCASummary.FDaySeparationRatio, ...
    PCASummary.MDaySeparationRatio
];

bar(comparisonValues);

xticks(1:height(PCASummary));

xticklabels({
    'Frequency'
    'Time'
    'Combined'
});

ylabel('Between / Within Cluster Distance');

legend( ...
    'FDay', ...
    'MDay', ...
    'Location', ...
    'best');

title('PCA User Separation by Feature Domain');

grid on;

exportgraphics( ...
    fig5, ...
    fullfile( ...
    figureDir, ...
    'pca_domain_separation.png'), ...
    'Resolution', 300);

close(fig5);

%% Console output

fprintf('\nPCA analysis complete.\n\n');

disp(PCASummary);

fprintf('\nKey dimensionality results:\n');

for r = 1:height(PCASummary)

    fprintf( ...
        '%-12s | PC1+PC2 %.2f%% | 90%% PCs %d | 95%% PCs %d | FDay Sep %.3f | MDay Sep %.3f\n', ...
        PCASummary.Domain{r}, ...
        PCASummary.PC1PC2VariancePercent(r), ...
        PCASummary.PCsFor90Percent(r), ...
        PCASummary.PCsFor95Percent(r), ...
        PCASummary.FDaySeparationRatio(r), ...
        PCASummary.MDaySeparationRatio(r));
end

fprintf('\nImportant methodology note:\n');
fprintf('PCA was fitted using FDay only.\n');
fprintf('MDay was projected using the fixed FDay transformation.\n');

fprintf('\nGenerated Stage 3 evidence successfully.\n');