%% Robustness and anomaly analysis
clear;
clc;
close all;

scriptPath = mfilename('fullpath');
projectRoot = fileparts(fileparts(scriptPath));

dataDir = fullfile(projectRoot, 'CW-Data');
tableDir = fullfile(projectRoot, 'results', 'tables');
figureDir = fullfile(projectRoot, 'results', 'figures');

if ~exist(tableDir, 'dir')
    mkdir(tableDir);
end

if ~exist(figureDir, 'dir')
    mkdir(figureDir);
end

%% Locked final configuration

domain = 'TimeD_FreqD';
hiddenLayers = [48 24];
repeats = 10;
maxEpochs = 400;

allUsers = 1:10;
excludedUser = 7;

remainingUsers = ...
    allUsers(allUsers ~= excludedUser);

remainingUserNames = ...
    compose('U%02d', remainingUsers);

%% Load locked mRMR features

featureFile = fullfile( ...
    tableDir, ...
    'selected_mrmr_features.csv');

featureTable = readtable(featureFile);

selectedFeatures = ...
    featureTable.Feature;

fprintf('\nStage 8 - Robustness Analysis\n');
fprintf('=============================\n\n');

fprintf('Locked domain       : %s\n', domain);
fprintf('Locked features     : %d\n', numel(selectedFeatures));
fprintf('Locked architecture : [48 24]\n');
fprintf('Sensitivity test    : exclude U07\n');
fprintf('Repeats             : %d\n\n', repeats);

%% Load FDay and MDay

[XFDay, yFDayOriginal] = ...
    loadDomainData( ...
        dataDir, ...
        domain, ...
        'FDay', ...
        allUsers);

[XMDay, yMDayOriginal] = ...
    loadDomainData( ...
        dataDir, ...
        domain, ...
        'MDay', ...
        allUsers);

%% Remove U07

trainMask = ...
    yFDayOriginal ~= excludedUser;

testMask = ...
    yMDayOriginal ~= excludedUser;

XFDay9 = ...
    XFDay(trainMask, selectedFeatures);

XMDay9 = ...
    XMDay(testMask, selectedFeatures);

yFDayOriginal9 = ...
    yFDayOriginal(trainMask);

yMDayOriginal9 = ...
    yMDayOriginal(testMask);

%% Remap original user IDs to 1..9

yFDay9 = zeros(size(yFDayOriginal9));
yMDay9 = zeros(size(yMDayOriginal9));

for i = 1:numel(remainingUsers)

    originalUser = remainingUsers(i);

    yFDay9(yFDayOriginal9 == originalUser) = i;
    yMDay9(yMDayOriginal9 == originalUser) = i;
end

fprintf('FDay samples without U07 : %d\n', size(XFDay9, 1));
fprintf('MDay samples without U07 : %d\n\n', size(XMDay9, 1));

%% Standardisation from FDay only

mu = mean(XFDay9, 1);
sigma = std(XFDay9, 0, 1);

sigma(sigma == 0) = 1;

XTrainZ = ...
    (XFDay9 - mu) ./ sigma;

XTestZ = ...
    (XMDay9 - mu) ./ sigma;

targets = ...
    full(ind2vec(yFDay9'));

%% U07 exclusion sensitivity experiment

runRows = cell(repeats, 11);

userRows = cell( ...
    repeats * numel(remainingUsers), ...
    11);

userRow = 1;

for repeat = 1:repeats

    fprintf( ...
        'U07 exclusion repeat %d/%d\n', ...
        repeat, repeats);

    rng(12100 + repeat, 'twister');

    network = patternnet( ...
        hiddenLayers, ...
        'trainscg');

    network.performFcn = 'crossentropy';
    network.divideFcn = 'dividetrain';

    network.trainParam.epochs = maxEpochs;
    network.trainParam.showWindow = false;
    network.trainParam.showCommandLine = false;

    network.inputs{1}.processFcns = {};

    network = train( ...
        network, ...
        XTrainZ', ...
        targets);

    scores = ...
        network(XTestZ');

    [metrics, userMetrics] = ...
        authenticationMetrics( ...
        yMDay9, ...
        scores);

    runRows(repeat, :) = { ...
        repeat, ...
        metrics.Accuracy, ...
        metrics.MacroPrecision, ...
        metrics.MacroRecall, ...
        metrics.MacroF1, ...
        metrics.MacroSpecificity, ...
        metrics.MeanFAR, ...
        metrics.MeanFRR, ...
        metrics.MeanEER, ...
        metrics.MeanAUC, ...
        numel(remainingUsers) ...
        };

    for i = 1:numel(remainingUsers)

        userRows(userRow, :) = { ...
            repeat, ...
            remainingUserNames{i}, ...
            userMetrics.Accuracy(i), ...
            userMetrics.Precision(i), ...
            userMetrics.Recall(i), ...
            userMetrics.Specificity(i), ...
            userMetrics.F1(i), ...
            userMetrics.FAR(i), ...
            userMetrics.FRR(i), ...
            userMetrics.EER(i), ...
            userMetrics.AUC(i) ...
            };

        userRow = userRow + 1;
    end
end

%% Save exclusion runs

U07ExclusionRuns = cell2table( ...
    runRows, ...
    'VariableNames', { ...
    'Repeat', ...
    'Accuracy', ...
    'MacroPrecision', ...
    'MacroRecall', ...
    'MacroF1', ...
    'MacroSpecificity', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC', ...
    'Users' ...
    });

writetable( ...
    U07ExclusionRuns, ...
    fullfile( ...
        tableDir, ...
        'u07_exclusion_runs.csv'));

%% U07 exclusion summary

U07ExclusionSummary = table( ...
    9, ...
    excludedUser, ...
    numel(selectedFeatures), ...
    string('48-24'), ...
    repeats, ...
    mean(U07ExclusionRuns.Accuracy), ...
    std(U07ExclusionRuns.Accuracy), ...
    mean(U07ExclusionRuns.MacroPrecision), ...
    mean(U07ExclusionRuns.MacroRecall), ...
    mean(U07ExclusionRuns.MacroF1), ...
    std(U07ExclusionRuns.MacroF1), ...
    mean(U07ExclusionRuns.MeanFAR), ...
    mean(U07ExclusionRuns.MeanFRR), ...
    mean(U07ExclusionRuns.MeanEER), ...
    mean(U07ExclusionRuns.MeanAUC), ...
    'VariableNames', { ...
    'Users', ...
    'ExcludedUser', ...
    'FeatureCount', ...
    'Architecture', ...
    'Repeats', ...
    'MeanAccuracy', ...
    'SDAccuracy', ...
    'MeanMacroPrecision', ...
    'MeanMacroRecall', ...
    'MeanMacroF1', ...
    'SDMacroF1', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC' ...
    });

writetable( ...
    U07ExclusionSummary, ...
    fullfile( ...
        tableDir, ...
        'u07_exclusion_summary.csv'));

%% Per-user exclusion summary

U07UserRuns = cell2table( ...
    userRows, ...
    'VariableNames', { ...
    'Repeat', ...
    'User', ...
    'Accuracy', ...
    'Precision', ...
    'Recall', ...
    'Specificity', ...
    'F1', ...
    'FAR', ...
    'FRR', ...
    'EER', ...
    'AUC' ...
    });

writetable( ...
    U07UserRuns, ...
    fullfile( ...
        tableDir, ...
        'u07_exclusion_user_runs.csv'));

summaryRows = cell(numel(remainingUsers), 10);

for i = 1:numel(remainingUsers)

    userName = remainingUserNames{i};

    idx = strcmp( ...
        string(U07UserRuns.User), ...
        string(userName));

    current = U07UserRuns(idx, :);

    summaryRows(i, :) = { ...
        userName, ...
        mean(current.Accuracy), ...
        mean(current.Precision), ...
        mean(current.Recall), ...
        mean(current.Specificity), ...
        mean(current.F1), ...
        mean(current.FAR), ...
        mean(current.FRR), ...
        mean(current.EER), ...
        mean(current.AUC) ...
        };
end

U07UserSummary = cell2table( ...
    summaryRows, ...
    'VariableNames', { ...
    'User', ...
    'Accuracy', ...
    'Precision', ...
    'Recall', ...
    'Specificity', ...
    'F1', ...
    'FAR', ...
    'FRR', ...
    'EER', ...
    'AUC' ...
    });

writetable( ...
    U07UserSummary, ...
    fullfile( ...
        tableDir, ...
        'u07_exclusion_user_summary.csv'));

%% Compare sensitivity with all-user final result

finalSummaryFile = fullfile( ...
    tableDir, ...
    'final_crossday_summary.csv');

FinalSummary = readtable(finalSummaryFile);

optimizedIndex = strcmp( ...
    string(FinalSummary.Model), ...
    "Optimized");

AllUserFinal = ...
    FinalSummary(optimizedIndex, :);

Setup = [
    "All 10 users"
    "U07 excluded"
];

Accuracy = [
    AllUserFinal.MeanAccuracy
    U07ExclusionSummary.MeanAccuracy
];

MacroPrecision = [
    AllUserFinal.MeanMacroPrecision
    U07ExclusionSummary.MeanMacroPrecision
];

MacroRecall = [
    AllUserFinal.MeanMacroRecall
    U07ExclusionSummary.MeanMacroRecall
];

MacroF1 = [
    AllUserFinal.MeanMacroF1
    U07ExclusionSummary.MeanMacroF1
];

FAR = [
    AllUserFinal.MeanFAR
    U07ExclusionSummary.MeanFAR
];

FRR = [
    AllUserFinal.MeanFRR
    U07ExclusionSummary.MeanFRR
];

EER = [
    AllUserFinal.MeanEER
    U07ExclusionSummary.MeanEER
];

U07SensitivityComparison = table( ...
    Setup, ...
    Accuracy, ...
    MacroPrecision, ...
    MacroRecall, ...
    MacroF1, ...
    FAR, ...
    FRR, ...
    EER);

writetable( ...
    U07SensitivityComparison, ...
    fullfile( ...
        tableDir, ...
        'u07_sensitivity_comparison.csv'));

%% Difficult-user diagnostic analysis

finalUserFile = fullfile( ...
    tableDir, ...
    'final_optimized_user_summary.csv');

FinalUsers = readtable(finalUserFile);

driftFile = fullfile( ...
    tableDir, ...
    'cross_day_user_drift.csv');

Drift = readtable(driftFile);

driftIndex = strcmp( ...
    string(Drift.Domain), ...
    domain);

Drift = Drift(driftIndex, :);

pcaDriftFile = fullfile( ...
    tableDir, ...
    'pca_user_crossday_drift.csv');

PCADrift = readtable(pcaDriftFile);

pcaIndex = strcmp( ...
    string(PCADrift.Domain), ...
    domain);

PCADrift = PCADrift(pcaIndex, :);

diagnosticRows = cell(10, 10);

for u = 1:10

    userName = sprintf('U%02d', u);

    finalIndex = strcmp( ...
        string(FinalUsers.User), ...
        userName);

    driftUserIndex = strcmp( ...
        string(Drift.User), ...
        userName);

    pcaUserIndex = strcmp( ...
        string(PCADrift.User), ...
        userName);

    diagnosticRows(u, :) = { ...
        userName, ...
        FinalUsers.F1(finalIndex), ...
        FinalUsers.FAR(finalIndex), ...
        FinalUsers.FRR(finalIndex), ...
        FinalUsers.EER(finalIndex), ...
        FinalUsers.AUC(finalIndex), ...
        Drift.NormalizedCentroidDistance(driftUserIndex), ...
        Drift.MeanAbsoluteNormalizedShift(driftUserIndex), ...
        PCADrift.CentroidShift(pcaUserIndex), ...
        u == 7 ...
        };
end

UserDiagnostics = cell2table( ...
    diagnosticRows, ...
    'VariableNames', { ...
    'User', ...
    'FinalF1', ...
    'FinalFAR', ...
    'FinalFRR', ...
    'FinalEER', ...
    'FinalAUC', ...
    'NormalizedCentroidDistance', ...
    'MeanAbsoluteNormalizedShift', ...
    'PCACentroidShift', ...
    'KnownExactDuplicate' ...
    });

UserDiagnostics = sortrows( ...
    UserDiagnostics, ...
    'FinalF1', ...
    'ascend');

writetable( ...
    UserDiagnostics, ...
    fullfile( ...
        tableDir, ...
        'user_robustness_diagnostics.csv'));

%% Exploratory correlations

nonDuplicate = ...
    ~UserDiagnostics.KnownExactDuplicate;

driftValues = ...
    UserDiagnostics.NormalizedCentroidDistance(nonDuplicate);

f1Values = ...
    UserDiagnostics.FinalF1(nonDuplicate);

frrValues = ...
    UserDiagnostics.FinalFRR(nonDuplicate);

eerValues = ...
    UserDiagnostics.FinalEER(nonDuplicate);

rhoF1 = corr( ...
    driftValues, ...
    f1Values, ...
    'Type', ...
    'Spearman', ...
    'Rows', ...
    'complete');

rhoFRR = corr( ...
    driftValues, ...
    frrValues, ...
    'Type', ...
    'Spearman', ...
    'Rows', ...
    'complete');

rhoEER = corr( ...
    driftValues, ...
    eerValues, ...
    'Type', ...
    'Spearman', ...
    'Rows', ...
    'complete');

CorrelationSummary = table( ...
    ["F1"; "FRR"; "EER"], ...
    [rhoF1; rhoFRR; rhoEER], ...
    'VariableNames', { ...
    'PerformanceMetric', ...
    'SpearmanCorrelationWithCrossDayDrift' ...
    });

writetable( ...
    CorrelationSummary, ...
    fullfile( ...
        tableDir, ...
        'crossday_drift_correlations.csv'));

%% Figure - U07 sensitivity

fig1 = figure('Visible', 'off');

comparisonValues = [
    U07SensitivityComparison.Accuracy, ...
    U07SensitivityComparison.MacroF1
];

bar(comparisonValues);

xticks(1:2);

xticklabels({
    'All 10 Users'
    'U07 Excluded'
});

ylabel('Score');

legend( ...
    'Accuracy', ...
    'Macro-F1', ...
    'Location', ...
    'best');

title('U07 Sensitivity Analysis');

ylim([0 1]);

grid on;

exportgraphics( ...
    fig1, ...
    fullfile( ...
        figureDir, ...
        'u07_sensitivity.png'), ...
    'Resolution', ...
    300);

close(fig1);

%% Figure - cross-day drift vs final F1

fig2 = figure('Visible', 'off');

hold on;

for u = 1:height(UserDiagnostics)

    if ~UserDiagnostics.KnownExactDuplicate(u)

        scatter( ...
            UserDiagnostics.NormalizedCentroidDistance(u), ...
            UserDiagnostics.FinalF1(u), ...
            70, ...
            'filled');

        text( ...
            UserDiagnostics.NormalizedCentroidDistance(u), ...
            UserDiagnostics.FinalF1(u), ...
            ['  ' char(UserDiagnostics.User{u})]);
    end
end

hold off;

xlabel('Normalized Cross-Day Centroid Distance');
ylabel('Final Cross-Day F1');

title('Cross-Day Behavioural Drift versus Authentication F1');

grid on;

exportgraphics( ...
    fig2, ...
    fullfile( ...
        figureDir, ...
        'crossday_drift_vs_f1.png'), ...
    'Resolution', ...
    300);

close(fig2);

%% Figure - difficult users

fig3 = figure('Visible', 'off');

errorValues = [
    UserDiagnostics.FinalFAR, ...
    UserDiagnostics.FinalFRR, ...
    UserDiagnostics.FinalEER
];

bar(errorValues);

xticks(1:height(UserDiagnostics));

xticklabels( ...
    UserDiagnostics.User);

xtickangle(45);

ylabel('Error Rate');

legend( ...
    'FAR', ...
    'FRR', ...
    'EER', ...
    'Location', ...
    'best');

title('User-Level Cross-Day Authentication Errors');

grid on;

exportgraphics( ...
    fig3, ...
    fullfile( ...
        figureDir, ...
        'robustness_user_errors.png'), ...
    'Resolution', ...
    300);

close(fig3);

%% Console summary

fprintf('\nU07 sensitivity analysis complete.\n\n');

disp(U07SensitivityComparison);

fprintf('\nU07 exclusion summary:\n\n');

disp(U07ExclusionSummary);

fprintf('\nUsers ranked from lowest to highest final F1:\n\n');

disp(UserDiagnostics);

fprintf('\nExploratory cross-day drift correlations:\n\n');

disp(CorrelationSummary);

fprintf('\nImportant interpretation notes:\n');
fprintf('U07 was excluded only for sensitivity analysis.\n');
fprintf('The locked feature list and architecture were not changed.\n');
fprintf('No MDay result was used to tune the classifier.\n');
fprintf('Correlation analysis is exploratory because only 9 non-duplicate users remain.\n');

fprintf('\nGenerated Stage 8 evidence successfully.\n');

%% Local functions

function [XAll, labels] = ...
    loadDomainData(dataDir, domain, dayName, users)

    XAll = [];
    labels = [];

    for i = 1:numel(users)

        userID = users(i);

        filePath = fullfile( ...
            dataDir, ...
            sprintf( ...
            'U%02d_Acc_%s_%s.mat', ...
            userID, ...
            domain, ...
            dayName));

        S = load(filePath);

        variableNames = ...
            fieldnames(S);

        X = ...
            S.(variableNames{1});

        XAll = [
            XAll;
            X
        ];

        labels = [
            labels;
            repmat(userID, size(X, 1), 1)
        ];
    end
end


function [metrics, userTable] = ...
    authenticationMetrics(trueLabels, scores)

    classCount = size(scores, 1);

    predictedLabels = ...
        vec2ind(scores)';

    accuracy = ...
        mean(predictedLabels == trueLabels);

    userAccuracy = zeros(classCount, 1);
    precision = zeros(classCount, 1);
    recall = zeros(classCount, 1);
    specificity = zeros(classCount, 1);
    f1 = zeros(classCount, 1);
    far = zeros(classCount, 1);
    frr = zeros(classCount, 1);
    eer = zeros(classCount, 1);
    auc = zeros(classCount, 1);

    for u = 1:classCount

        genuine = ...
            trueLabels == u;

        acceptedAsUser = ...
            predictedLabels == u;

        TP = sum(genuine & acceptedAsUser);
        FN = sum(genuine & ~acceptedAsUser);

        FP = sum(~genuine & acceptedAsUser);
        TN = sum(~genuine & ~acceptedAsUser);

        userAccuracy(u) = ...
            (TP + TN) / ...
            (TP + TN + FP + FN + eps);

        precision(u) = ...
            TP / ...
            (TP + FP + eps);

        recall(u) = ...
            TP / ...
            (TP + FN + eps);

        specificity(u) = ...
            TN / ...
            (TN + FP + eps);

        f1(u) = ...
            2 * precision(u) * recall(u) / ...
            (precision(u) + recall(u) + eps);

        far(u) = ...
            FP / ...
            (FP + TN + eps);

        frr(u) = ...
            FN / ...
            (TP + FN + eps);

        binaryLabels = ...
            double(genuine);

        userScores = ...
            scores(u, :)';

        [rocFPR, rocTPR, ~, aucValue] = ...
            perfcurve( ...
            binaryLabels, ...
            userScores, ...
            1);

        rocFNR = ...
            1 - rocTPR;

        [~, eerIndex] = ...
            min(abs(rocFPR - rocFNR));

        eer(u) = ...
            (rocFPR(eerIndex) + ...
            rocFNR(eerIndex)) / 2;

        auc(u) = ...
            aucValue;
    end

    metrics = struct();

    metrics.Accuracy = ...
        accuracy;

    metrics.MacroPrecision = ...
        mean(precision);

    metrics.MacroRecall = ...
        mean(recall);

    metrics.MacroF1 = ...
        mean(f1);

    metrics.MacroSpecificity = ...
        mean(specificity);

    metrics.MeanFAR = ...
        mean(far);

    metrics.MeanFRR = ...
        mean(frr);

    metrics.MeanEER = ...
        mean(eer);

    metrics.MeanAUC = ...
        mean(auc);

    User = ...
        (1:classCount)';

    userTable = table( ...
        User, ...
        userAccuracy, ...
        precision, ...
        recall, ...
        specificity, ...
        f1, ...
        far, ...
        frr, ...
        eer, ...
        auc, ...
        'VariableNames', { ...
        'User', ...
        'Accuracy', ...
        'Precision', ...
        'Recall', ...
        'Specificity', ...
        'F1', ...
        'FAR', ...
        'FRR', ...
        'EER', ...
        'AUC' ...
        });
end