%% Neural network architecture optimisation
clear;
clc;
close all;

scriptPath = mfilename('fullpath');
projectRoot = fileparts(fileparts(scriptPath));

dataDir = fullfile(projectRoot, 'CW-Data');
tableDir = fullfile(projectRoot, 'results', 'tables');
figureDir = fullfile(projectRoot, 'results', 'figures');

if ~exist(tableDir, 'dir')
    mkdir(tableDir);
end

if ~exist(figureDir, 'dir')
    mkdir(figureDir);
end

%% Configuration

users = compose('U%02d', 1:10);

domain = 'TimeD_FreqD';

architectures = {
    'H12',     [12]
    'H24',     [24]
    'H48',     [48]
    'H72',     [72]
    'H48_24',  [48 24]
    'H64_32',  [64 32]
};

repeats = 5;
validationSamplesPerUser = 8;
maxEpochs = 400;

fprintf('\nStage 5 - Architecture Optimisation\n');
fprintf('===================================\n\n');

fprintf('Feature domain: %s\n', domain);
fprintf('Architectures : %d\n', size(architectures, 1));
fprintf('Repeats       : %d\n', repeats);
fprintf('Total networks: %d\n\n', ...
    size(architectures, 1) * repeats);

%% Load FDay only

[X, labels] = loadDomainData( ...
    dataDir, ...
    domain, ...
    'FDay', ...
    users);

inputFeatures = size(X, 2);

fprintf('FDay samples  : %d\n', size(X, 1));
fprintf('Input features: %d\n\n', inputFeatures);

%% Architecture experiments

resultRows = cell(0, 14);
resultRow = 1;

for a = 1:size(architectures, 1)

    architectureName = architectures{a, 1};
    hiddenLayers = architectures{a, 2};

    fprintf( ...
        'Testing %-8s architecture ', ...
        architectureName);

    fprintf('[');

    fprintf('%d ', hiddenLayers);

    fprintf(']\n');

    parameterCount = countNetworkParameters( ...
        inputFeatures, ...
        hiddenLayers, ...
        10);

    for repeat = 1:repeats

        %% Identical split for every architecture

        rng(5200 + repeat, 'twister');

        trainMask = false(size(labels));
        validationMask = false(size(labels));

        for u = 1:10

            userIndices = find(labels == u);

            order = randperm(numel(userIndices));

            validationIndices = ...
                userIndices( ...
                order(1:validationSamplesPerUser));

            trainingIndices = ...
                userIndices( ...
                order(validationSamplesPerUser + 1:end));

            validationMask(validationIndices) = true;
            trainMask(trainingIndices) = true;
        end

        XTrain = X(trainMask, :);
        yTrain = labels(trainMask);

        XValidation = X(validationMask, :);
        yValidation = labels(validationMask);

        %% Training-only standardisation

        mu = mean(XTrain, 1);
        sigma = std(XTrain, 0, 1);

        sigma(sigma == 0) = 1;

        XTrainZ = ...
            (XTrain - mu) ./ sigma;

        XValidationZ = ...
            (XValidation - mu) ./ sigma;

        %% Independent network initialisation

        rng( ...
            6200 + ...
            a * 100 + ...
            repeat, ...
            'twister');

        network = patternnet( ...
            hiddenLayers, ...
            'trainscg');

        network.performFcn = 'crossentropy';
        network.divideFcn = 'dividetrain';

        network.trainParam.epochs = maxEpochs;
        network.trainParam.showWindow = false;
        network.trainParam.showCommandLine = false;

        network.inputs{1}.processFcns = {};

        targets = ...
            full(ind2vec(yTrain'));

        network = train( ...
            network, ...
            XTrainZ', ...
            targets);

        %% FDay validation

        validationScores = ...
            network(XValidationZ');

        metrics = ...
            authenticationMetrics( ...
            yValidation, ...
            validationScores);

        resultRows(resultRow, :) = { ...
            architectureName, ...
            architectureText(hiddenLayers), ...
            parameterCount, ...
            repeat, ...
            metrics.Accuracy, ...
            metrics.MacroPrecision, ...
            metrics.MacroRecall, ...
            metrics.MacroF1, ...
            metrics.MacroSpecificity, ...
            metrics.MeanFAR, ...
            metrics.MeanFRR, ...
            metrics.MeanEER, ...
            metrics.MeanAUC, ...
            size(XTrain, 1) ...
            };

        resultRow = resultRow + 1;
    end
end

%% Save all runs

ArchitectureRuns = cell2table( ...
    resultRows, ...
    'VariableNames', { ...
    'Architecture', ...
    'HiddenLayers', ...
    'ParameterCount', ...
    'Repeat', ...
    'Accuracy', ...
    'MacroPrecision', ...
    'MacroRecall', ...
    'MacroF1', ...
    'MacroSpecificity', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC', ...
    'TrainingSamples' ...
    });

writetable( ...
    ArchitectureRuns, ...
    fullfile( ...
    tableDir, ...
    'architecture_optimization_runs.csv'));

%% Summarise architectures

summaryRows = cell(size(architectures, 1), 14);

for a = 1:size(architectures, 1)

    architectureName = architectures{a, 1};

    idx = strcmp( ...
        ArchitectureRuns.Architecture, ...
        architectureName);

    current = ArchitectureRuns(idx, :);

    summaryRows(a, :) = { ...
        architectureName, ...
        current.HiddenLayers{1}, ...
        current.ParameterCount(1), ...
        mean(current.Accuracy), ...
        std(current.Accuracy), ...
        mean(current.MacroPrecision), ...
        mean(current.MacroRecall), ...
        mean(current.MacroF1), ...
        std(current.MacroF1), ...
        mean(current.MacroSpecificity), ...
        mean(current.MeanFAR), ...
        mean(current.MeanFRR), ...
        mean(current.MeanEER), ...
        mean(current.MeanAUC) ...
        };
end

ArchitectureSummary = cell2table( ...
    summaryRows, ...
    'VariableNames', { ...
    'Architecture', ...
    'HiddenLayers', ...
    'ParameterCount', ...
    'MeanAccuracy', ...
    'SDAccuracy', ...
    'MeanMacroPrecision', ...
    'MeanMacroRecall', ...
    'MeanMacroF1', ...
    'SDMacroF1', ...
    'MeanSpecificity', ...
    'MeanFAR', ...
    'MeanFRR', ...
    'MeanEER', ...
    'MeanAUC' ...
    });

%% Rank by Macro-F1

ArchitectureSummary = ...
    sortrows( ...
        ArchitectureSummary, ...
        {'MeanMacroF1', 'MeanEER'}, ...
        {'descend', 'ascend'});

Rank = ...
    (1:height(ArchitectureSummary))';

ArchitectureSummary = ...
    addvars( ...
        ArchitectureSummary, ...
        Rank, ...
        'Before', ...
        1);

writetable( ...
    ArchitectureSummary, ...
    fullfile( ...
    tableDir, ...
    'architecture_optimization_summary.csv'));

%% Selected architecture

selectedArchitecture = ...
    ArchitectureSummary.Architecture{1};

selectedLayersText = ...
    ArchitectureSummary.HiddenLayers{1};

selectedParameterCount = ...
    ArchitectureSummary.ParameterCount(1);

selectedMacroF1 = ...
    ArchitectureSummary.MeanMacroF1(1);

selectedEER = ...
    ArchitectureSummary.MeanEER(1);

SelectedArchitecture = table( ...
    string(domain), ...
    string(selectedArchitecture), ...
    string(selectedLayersText), ...
    selectedParameterCount, ...
    selectedMacroF1, ...
    selectedEER, ...
    'VariableNames', { ...
    'Domain', ...
    'Architecture', ...
    'HiddenLayers', ...
    'ParameterCount', ...
    'DevelopmentMacroF1', ...
    'DevelopmentEER' ...
    });

writetable( ...
    SelectedArchitecture, ...
    fullfile( ...
    tableDir, ...
    'selected_architecture.csv'));

%% Figure - Macro-F1

plotSummary = ...
    sortrows( ...
        ArchitectureSummary, ...
        'Rank', ...
        'ascend');

fig1 = figure('Visible', 'off');

bar(plotSummary.MeanMacroF1);

xticks(1:height(plotSummary));

xticklabels( ...
    plotSummary.Architecture);

xtickangle(30);

ylabel('Mean Macro-F1');

title( ...
    'FDay Neural Network Architecture Comparison');

grid on;

exportgraphics( ...
    fig1, ...
    fullfile( ...
    figureDir, ...
    'architecture_macro_f1.png'), ...
    'Resolution', 300);

close(fig1);

%% Figure - EER

fig2 = figure('Visible', 'off');

bar(plotSummary.MeanEER);

xticks(1:height(plotSummary));

xticklabels( ...
    plotSummary.Architecture);

xtickangle(30);

ylabel('Mean EER');

title( ...
    'FDay Architecture Equal Error Rate');

grid on;

exportgraphics( ...
    fig2, ...
    fullfile( ...
    figureDir, ...
    'architecture_eer.png'), ...
    'Resolution', 300);

close(fig2);

%% Figure - complexity versus F1

fig3 = figure('Visible', 'off');

scatter( ...
    plotSummary.ParameterCount, ...
    plotSummary.MeanMacroF1, ...
    70, ...
    'filled');

hold on;

for i = 1:height(plotSummary)

    text( ...
        plotSummary.ParameterCount(i), ...
        plotSummary.MeanMacroF1(i), ...
        ['  ' plotSummary.Architecture{i}], ...
        'VerticalAlignment', ...
        'middle');
end

hold off;

xlabel('Trainable Parameter Count');
ylabel('Mean Macro-F1');

title( ...
    'Architecture Complexity versus Performance');

grid on;

exportgraphics( ...
    fig3, ...
    fullfile( ...
    figureDir, ...
    'architecture_complexity_vs_f1.png'), ...
    'Resolution', 300);

close(fig3);

%% Console summary

fprintf('\nArchitecture optimisation complete.\n\n');

disp(ArchitectureSummary);

fprintf('\nSelected architecture:\n');

fprintf( ...
    '%s = %s\n', ...
    selectedArchitecture, ...
    selectedLayersText);

fprintf( ...
    'Parameters : %d\n', ...
    selectedParameterCount);

fprintf( ...
    'Macro-F1   : %.5f\n', ...
    selectedMacroF1);

fprintf( ...
    'Mean EER   : %.5f\n', ...
    selectedEER);

fprintf('\nImportant methodology note:\n');
fprintf('Only FDay data was used in Stage 5.\n');
fprintf('The same FDay splits were used for every architecture.\n');
fprintf('MDay was not used for architecture selection.\n');

fprintf('\nGenerated Stage 5 evidence successfully.\n');

%% Local functions

function [XAll, labels] = ...
    loadDomainData(dataDir, domain, dayName, users)

    XAll = [];
    labels = [];

    for u = 1:numel(users)

        filePath = fullfile( ...
            dataDir, ...
            sprintf( ...
            '%s_Acc_%s_%s.mat', ...
            users{u}, ...
            domain, ...
            dayName));

        S = load(filePath);

        variableNames = ...
            fieldnames(S);

        X = ...
            S.(variableNames{1});

        XAll = [
            XAll;
            X
        ];

        labels = [
            labels;
            repmat(u, size(X, 1), 1)
        ];
    end
end


function metrics = ...
    authenticationMetrics(trueLabels, scores)

    classCount = 10;

    predictedLabels = ...
        vec2ind(scores)';

    accuracy = ...
        mean(predictedLabels == trueLabels);

    precision = zeros(classCount, 1);
    recall = zeros(classCount, 1);
    specificity = zeros(classCount, 1);
    f1 = zeros(classCount, 1);
    far = zeros(classCount, 1);
    frr = zeros(classCount, 1);
    eer = zeros(classCount, 1);
    auc = zeros(classCount, 1);

    for u = 1:classCount

        genuine = ...
            trueLabels == u;

        acceptedAsUser = ...
            predictedLabels == u;

        TP = sum(genuine & acceptedAsUser);
        FN = sum(genuine & ~acceptedAsUser);

        FP = sum(~genuine & acceptedAsUser);
        TN = sum(~genuine & ~acceptedAsUser);

        precision(u) = ...
            TP / ...
            (TP + FP + eps);

        recall(u) = ...
            TP / ...
            (TP + FN + eps);

        specificity(u) = ...
            TN / ...
            (TN + FP + eps);

        f1(u) = ...
            2 * precision(u) * recall(u) / ...
            (precision(u) + recall(u) + eps);

        far(u) = ...
            FP / ...
            (FP + TN + eps);

        frr(u) = ...
            FN / ...
            (TP + FN + eps);

        binaryLabels = ...
            double(genuine);

        userScores = ...
            scores(u, :)';

        [rocFPR, rocTPR, ~, aucValue] = ...
            perfcurve( ...
            binaryLabels, ...
            userScores, ...
            1);

        rocFNR = ...
            1 - rocTPR;

        [~, eerIndex] = ...
            min(abs(rocFPR - rocFNR));

        eer(u) = ...
            (rocFPR(eerIndex) + ...
            rocFNR(eerIndex)) / 2;

        auc(u) = aucValue;
    end

    metrics = struct();

    metrics.Accuracy = accuracy;
    metrics.MacroPrecision = mean(precision);
    metrics.MacroRecall = mean(recall);
    metrics.MacroF1 = mean(f1);
    metrics.MacroSpecificity = mean(specificity);
    metrics.MeanFAR = mean(far);
    metrics.MeanFRR = mean(frr);
    metrics.MeanEER = mean(eer);
    metrics.MeanAUC = mean(auc);
end


function count = ...
    countNetworkParameters( ...
    inputCount, ...
    hiddenLayers, ...
    outputCount)

    count = 0;

    previousLayer = inputCount;

    for i = 1:numel(hiddenLayers)

        currentLayer = hiddenLayers(i);

        count = ...
            count + ...
            previousLayer * currentLayer + ...
            currentLayer;

        previousLayer = ...
            currentLayer;
    end

    count = ...
        count + ...
        previousLayer * outputCount + ...
        outputCount;
end


function textValue = ...
    architectureText(hiddenLayers)

    pieces = ...
        arrayfun( ...
            @(x) sprintf('%d', x), ...
            hiddenLayers, ...
            'UniformOutput', ...
            false);

    textValue = ...
        strjoin(pieces, '-');
end